#!/usr/bin/env bash

# This script runs verbmhist on all files in a directory

declare -r helpMsg="Usage: <source file directory> <num of most common words> <sort by avg>";
declare -r sourceFileDir="${1}";
declare -r numOfMaxOcc="${2}";
declare -r sortByAvg="${3}";

if [[ ! -d "${sourceFileDir}" ]]; then
	echo "The source file directory: '${sourceFileDir}' does not exist!";
	echo "${helpMsg}";
	exit 1;
fi

if [[ -z "${numOfMaxOcc}" ]]; then
	echo "The number of the most commonly occurring words was not specified!";
	echo "${helpMsg}";
	exit 1;
fi

if [[ "${sortByAvg}" != "yes" && "${sortByAvg}" != "no" ]]; then
	echo "The sortByAvg parameter must be either 'yes', or 'no'!";
	echo "${helpMsg}";
	exit 1;
fi

sourceFileList="$(ls ${sourceFileDir})";

for file in ${sourceFileList}; do
	echo -n "Running verbmhist on: ${sourceFileDir}/${file}...";
	./build/src/verbmhist "${sourceFileDir}/${file}" "${numOfMaxOcc}" "${sourceFileDir}/HIST_${file}" "${sortByAvg}";

	if [[ "$?" == "0" ]]; then
		echo " done.";
	else
		exit 1;
	fi
done
