#!/usr/bin/env bash

# This script runs verbmhist on all files in a directory

declare -r helpMsg="Usage: <source file dir> <output dir> <num of most common words>";
declare -r sourceFileDir="${1}";
declare -r outputDir="${2}";
declare -r numOfMaxOcc="${3}";

if [[ ! -d "${sourceFileDir}" ]]; then
	echo "The source file directory: '${sourceFileDir}' does not exist!";
	echo "${helpMsg}";
	exit 1;
fi

if [[ ! -d "${outputDir}" ]]; then
	echo "The output directory: '${outputDir}' does not exist!";
	echo "${helpMsg}";
	exit 1;
fi

if [[ -z "${numOfMaxOcc}" ]]; then
	echo "The number of the most commonly occurring words was not specified!";
	echo "${helpMsg}";
	exit 1;
fi

sourceFileList="$(ls ${sourceFileDir})";

for file in ${sourceFileList}; do
	echo -n "Analyzing file: ${sourceFileDir}/${file}...";
	if [[ ! -d "${outputDir}/${file%.*}" ]]; then
		mkdir -p ${outputDir}/${file%.*};
	else
		echo "The directory: '${outputDir}/${file%.*}' already exists. Skipping...";
		continue;
	fi

	./build/src/verbmeter "${sourceFileDir}/${file}" "${outputDir}/${file%.*}" "${numOfMaxOcc}";

	if [[ "$?" == "0" ]]; then
		echo " done.";
	else
		exit 1;
	fi
done
